config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'buildings#index'

  namespace :admin do
    root to: 'dashboard#index'
    resources :buildings do
      resources :rooms do
        resources :lessons
      end
    end
    resources :students
    resources :teachers
    resources :courses
    get 'buildings/:id/overview', to: 'buildings#overview', as: 'overview_building'
    get 'lessons', to: 'lessons#all', as: 'all_lessons'
    get 'rooms', to: 'rooms#all', as: 'all_rooms'
  end

  resources :buildings do
    resources :rooms do
      resources :lessons
    end
  end

  get 'buildings/:id/overview', to: 'buildings#overview', as: 'overview_building'

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :building
  has_many :lessons

  validates :title, presence: true, length: { minimum: 3 }
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < AdminController

  before_action :find_building
  before_action :heading_name

  def index
    @rooms = @building.rooms
    render 'empty' if @rooms.empty?
  end

  def all
    @rooms = Room.all
    render 'empty' if @rooms.empty?
  end

  def show
    @room = Room.find(params[:id])
  end

  def new
    @room = Room.new
  end

  def create
    @room = @building.rooms.build(room_params)
    @room.save!
    redirect_to admin_building_room_path(@building, @room)
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.update(room_params)
    redirect_to admin_building_room_path(@building, @room)
  end

  def destroy
    @room = Room.find(params[:id]).delete
    redirect_to :index
  end

  private

  def heading_name
    @heading_name = "#{@building&.title}: Rooms"
  end

  def room_params
    params.require(:fake).permit(:title, :code)
  end

  def find_building
    @building = Building.find_by id: params[:building_id]
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :find_building
  before_action :heading_name

  def index
    @rooms = @building.rooms
    render 'empty' if @rooms.empty?
  end

  def show
    @room = Room.find(params[:id])
  end

  # def new
  #   @room = Room.new
  # end
  #
  # def create
  #   @room = @building.rooms.build(room_params)
  #   @room.save!
  #   redirect_to admin_building_room_path(@building, @room)
  # end
  #
  # def edit
  #   @room = Room.find(params[:id])
  # end
  #
  # def update
  #   @room = Room.update(room_params)
  #   redirect_to admin_room_path @room
  # end
  #
  # def destroy
  #   @room = Room.find(params[:id]).delete
  #   redirect_to :index
  # end

  private

  def heading_name
    @heading_name = "#{@building.title}: Rooms"
  end

  def room_params
    params.require(:fake).permit(:title, :code)
  end

  def find_building
    @building = Building.find params[:building_id]
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/admin/rooms/_form.html.erb
<%= simple_form_for [@building, @room], url: admin_building_room_path(@building, @room), as: :fake do |f| %>
  <%= f.input :title %>

  <%= f.input :code %>

  <%= f.button :submit %>
<% end %>

app/views/admin/rooms/_room.html.erb
<div class="box">
  <h3 class="boxes button">
    <%= link_to room.title, admin_building_room_lessons_path(room.building, room) %>
  </h3>
  <p> code: <%= room.code %> </p>
  <%= link_to 'edit', edit_admin_building_room_path(room.building, room) %>
  <%= link_to 'delete', admin_building_room_path(room.building, room), data: {confirm: 'Are you sure?'}, method: :delete %>
</div>

app/views/admin/rooms/all.html.erb
<%= render @rooms %>
<%= link_to 'dashboard', admin_root_path %>

app/views/admin/rooms/edit.html.erb
<%= render 'form' %>
<%= link_to 'delete', admin_building_room_path(@building, @room), method: :delete %>

app/views/admin/rooms/empty.html.erb
<p> No rooms found! </p>

app/views/admin/rooms/index.html.erb
<%= render @rooms %>

app/views/admin/rooms/new.html.erb
<%= render 'form' %>

app/views/admin/rooms/show.html.erb
<%= render @room %>