config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'buildings#index'

  namespace :admin do
    root to: 'dashboard#index'
    resources :buildings do
      resources :rooms do
        resources :lessons
      end
    end
    resources :students
    resources :teachers
    resources :courses
    get 'buildings/:id/overview', to: 'buildings#overview', as: 'overview_building'
    get 'lessons', to: 'lessons#all', as: 'all_lessons'
    get 'rooms', to: 'rooms#all', as: 'all_rooms'
  end

  resources :buildings do
    resources :rooms do
      resources :lessons
    end
  end

  get 'buildings/:id/overview', to: 'buildings#overview', as: 'overview_building'

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :room
  belongs_to :teacher
  belongs_to :course

  validates :duration, presence: true, numericality: { only_integer: true }


  before_validation :calculate_end_time
  validate :check_for_time_collisions

  def self.this_week
    if Time.zone.now.wday != 0
      where start_at: ((Time.zone.now.beginning_of_week - 1.day)..(Time.zone.now.end_of_week - 1.day))
    else
      where start_at: (Time.zone.now.beginning_of_day..(Time.zone.now.beginning_of_day + 7.days))
    end
  end

  def self.today
    where start_at: (Time.zone.now.beginning_of_day..(Time.zone.now.beginning_of_day))
  end

  def day
    start_at.wday
  end

  def day_of_week
    Date::DAYNAMES[day]
  end

  def in_hour?(hour)
    start_at.hour <= hour && end_at.hour > hour
  end


  private

  def check_for_time_collisions
    lessons_this_week = room.lessons.this_week
    lessons_this_week.each do |lesson|
      if collide?(lesson)
        errors.add(:start_at, 'lesson collision')
      end
    end
  end

  def collide?(lesson)
    (start_at..end_at).overlaps?(lesson.start_at..lesson.end_at)
  end

  def calculate_end_time
    self.end_at = start_at + duration.hour.seconds
  end
end



=begin
 def this_week
    where start_at: (start_at.beginning_of_week..start_at.end_of_week)
 end
=end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < AdminController

  before_action :find_room_and_building
  before_action :heading_name

  def index
    @lessons = @room.lessons.this_week.includes(:course).order(start_at: :asc)
    render 'empty' if @lessons.empty?
  end

  def all
    @lessons = Lesson.all
    render 'empty' if @lessons.empty?
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def new
    @lesson = Lesson.new
  end

  def create

    @lesson = @room.lessons.build(lesson_params)

    if @lesson.save
      redirect_to admin_building_room_lessons_path(@building, @room)
    else
      render 'new'
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.update(lesson_params)
    redirect_to admin_building_room_lesson_path(@building, @room, @lesson)
  end

  def destroy
    @lesson = Lesson.find(params[:id]).delete
    redirect_to :index
  end

  private

  def heading_name
    @heading_name = "#{@room&.title}: Schedule"
  end

  def lesson_params
    params.require(:faker).permit(:start_at, :duration, :teacher_id, :course_id)
  end

  def find_room_and_building
    @building = Building.find_by id: params[:building_id]
    @room = Room.find_by id: params[:room_id]
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  before_action :find_room_and_building
  before_action :heading_name

  def index
    @lessons = @room.lessons.this_week.includes(:course).order(start_at: :asc)
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  private

  def heading_name
    @heading_name = "#{@room.title}: Schedule"
  end

  def lesson_params
    params.require(:faker).permit(:start_at, :duration)
  end

  def find_room_and_building
    @building = Building.find params[:building_id]
    @room = Room.find params[:room_id]
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper

  def generate_hours(lessons)
    html = ''
    8.times do |hour|
      html << "<td>#{find_name(lessons, hour + 8)}</td>"
    end
    html.html_safe
  end

  private

  def find_name(lessons, hour)
    lessons.each do |lesson|
      return lesson.course.title if lesson.in_hour?(hour)
    end
    ""
  end
end

app/views/admin/lessons/_lesson.html.erb
<div class="box">
  <h3 class="boxes button">
    <%= link_to lesson.course.title, admin_building_room_lessons_path(lesson.room.building, lesson.room, lesson) %>
  </h3>
  <p> code: <%= lesson.course.code %> </p>
  <%= link_to 'edit', edit_admin_building_room_lesson_path(lesson.room.building, lesson.room, lesson) %>
  <%= link_to 'delete', admin_building_room_lesson_path(lesson.room.building, lesson.room, lesson), data: {confirm: 'Are you sure?'}, method: :delete %>
</div>

app/views/admin/lessons/all.html.erb
<%= render @lessons %>
<%= link_to 'dashboard', admin_root_path %>

app/views/admin/lessons/edit.html.erb
<%= simple_form_for [@building, @room, @lesson], url: admin_building_room_lessons_path(@building, @room, @lesson), method: :patch, as: :faker do |f| %>
  <%= f.input :start_at, as: :datetime, minute_step: 60 %>

  <%= f.input :duration, collection: 1..8, include_blank: false %>

  <%= f.association :course %>

  <%= f.association :teacher, collection: @lesson.course&.teachers || Teacher.none %>

  <%= f.button :submit %>
<% end %>
<%= link_to 'delete', admin_building_room_lesson_path(@building, @room, @lesson), method: :delete %>

app/views/admin/lessons/empty.html.erb
<p> No lessons found! </p>

app/views/admin/lessons/index.html.erb
<div>
  <%= render @lessons %>
  <table style="width: 100%">
    <tr>
      <th>Days / Time</th>
      <th>8:00 - 9:00</th>
      <th>10:00 - 11:00</th>
      <th>11:00 - 12:00</th>
      <th>13:00 - 14:00</th>
      <th>14:00 - 15:00</th>
      <th>15:00 - 16:00</th>
      <th>16:00 - 17:00</th>
      <th>18:00 - 19:00</th>
    </tr>
    <% 7.times do |day| %>
      <% current_lessons = @lessons.select{|l| l.day == day}  %>
      <tr>
        <td>
          <%= Date::DAYNAMES[day] %>
        </td>
        <%= generate_hours(current_lessons) %>
      </tr>
    <% end %>
  </table>
  <%= link_to 'New', new_admin_building_room_lesson_path(@building, @room) %>
</div>

app/views/admin/lessons/new.html.erb
<%= simple_form_for [@building, @room, @lesson], url: admin_building_room_lessons_path(@building, @room, @lesson), method: :post, as: :faker do |f| %>
  <%= f.input :start_at, as: :datetime, minute_step: 60 %>

  <%= f.input :duration, collection: 1..8, include_blank: false %>

  <%= f.association :course %>

  <%= f.association :teacher, collection: Teacher.all %>

  <%= f.button :submit %>
<% end %>

app/views/admin/lessons/show.html.erb
<%= render @lesson %>

<p> Students: <%= @lesson.course.students.map(&:to_s).join(", ") %> </p>