config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'buildings#index'

  namespace :admin do
    root to: 'dashboard#index'
    resources :buildings do
      resources :rooms do
        resources :lessons
      end
    end
    resources :students
    resources :teachers
    resources :courses
    get 'buildings/:id/overview', to: 'buildings#overview', as: 'overview_building'
    get 'lessons', to: 'lessons#all', as: 'all_lessons'
    get 'rooms', to: 'rooms#all', as: 'all_rooms'
  end

  resources :buildings do
    resources :rooms do
      resources :lessons
    end
  end

  get 'buildings/:id/overview', to: 'buildings#overview', as: 'overview_building'

end

app/models/building.rb
class Building < ApplicationRecord
  has_many :rooms

  validates :title, presence: true, length: { minimum: 3 }
end

app/controllers/admin/buildings_controller.rb
class Admin::BuildingsController < AdminController



  before_action :heading_name

  def index
    @buildings = Building.all
    render 'empty' if @buildings.empty?
  end

  def show
    @building = Building.find(params[:id])
  end

  def overview
    @building = Building.find(params[:id])
    @rooms = @building.rooms
  end

  def new
      @building = Building.new
  end

   def create
     @building = Building.new(building_params)
     if @building.save
       redirect_to admin_buildings_path(@building)
     else
       render 'new'
     end
   end

  def edit
    @building = Building.find(params[:id])
  end

  def update
    @building = Building.update(building_params)
    redirect_to admin_buildings_path @building
  end

  def destroy
    @building = Building.find(params[:id]).delete
    redirect_to :index
  end

  private

  def heading_name
    @heading_name = "Buildings"
  end

  def building_params
    params.require(:building).permit(:title, :code)
  end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

  before_action :heading_name

  def index
    @buildings = Building.all
    render 'empty' if @buildings.empty?
  end

  def show
    @building = Building.find(params[:id])
  end

  def overview
    @building = Building.find(params[:id])
    @rooms = @building.rooms
  end

  private

  def heading_name
    @heading_name = "Buildings"
  end

  def building_params
    params.require(:building).permit(:title, :code)
  end
end

app/helpers/buildings_helper.rb
module BuildingsHelper

  def room_invocation(lessons)
    html = ''
    8.times do |hour|
      html << "<td>#{find_name(lessons, hour + 8)}</td>"
    end
    html.html_safe
  end

  private

  def find_name(lessons, hour)
    lessons.each do |lesson|
      return "#{lesson.course.title} (#{lesson.course.students.count})" if lesson.in_hour?(hour)
    end
    ""
  end

end

app/views/admin/buildings/_building.html.erb
<div class="box">
  <h3 class="boxes button">
    <%= link_to building.title, admin_building_rooms_path(building) %>
  </h3>
  <p>
    <%= link_to 'overview', admin_overview_building_path(building) %>
  </p>
  <p> code: <%= building.code %> </p>
  <%= link_to 'edit', edit_admin_building_path(building) %>
  <%= link_to 'delete', admin_building_path(building), data: {confirm: 'Are you sure?'}, method: :delete %>
</div>

app/views/admin/buildings/edit.html.erb
<%= simple_form_for @building, url: admin_building_path(@building), method: :patch do |f| %>
  <%= f.input :title %>

  <%= f.input :code %>

  <%= f.button :submit %>
<% end %>
<%= link_to 'delete', admin_building_path(@building), method: :delete %>

app/views/admin/buildings/empty.html.erb
<p> No buildings found! </p>

app/views/admin/buildings/index.html.erb
<!--
<div>
  <aside class="side">
    <ul>
      <li>
        Menu
      </li>
      <li>
        Building 1
      </li>
      <li>
        Building 2
      </li>
      <li>
        Building 3
      </li>
    </ul>
  </aside>
</div>
-->

<%= render @buildings %>
<%= link_to 'New Building', new_admin_building_path %>
<%= link_to 'dashboard', admin_root_path %>

app/views/admin/buildings/new.html.erb
<%= simple_form_for @building, url: admin_buildings_path(@building), method: :post do |f| %>
  <%= f.input :title %>

  <%= f.input :code %>

  <%= f.button :submit %>
<% end %>

app/views/admin/buildings/overview.html.erb
<div>
  <table style="width: 100%">
    <tr>
      <th>Room / Time</th>
      <th>8:00 - 9:00</th>
      <th>10:00 - 11:00</th>
      <th>11:00 - 12:00</th>
      <th>13:00 - 14:00</th>
      <th>14:00 - 15:00</th>
      <th>15:00 - 16:00</th>
      <th>16:00 - 17:00</th>
      <th>18:00 - 19:00</th>
    </tr>
    <% @rooms.each do |room| %>
      <tr>
        <td>
          <%= room.title %>
        </td>
        <%= room_invocation(room.lessons.today) %>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/buildings/show.html.erb
<%= render @building %>